// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqW4Vbv2fxD-2tRjaFQG2k2gs2sVnWn5o',
    appId: '1:535166613531:web:8a4f31229c473299eba0be',
    messagingSenderId: '535166613531',
    projectId: 'cosmicbrain-1360a',
    authDomain: 'cosmicbrain-1360a.firebaseapp.com',
    storageBucket: 'cosmicbrain-1360a.firebasestorage.app',
    measurementId: 'G-GGNVS5GWV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPB3xWjDmRIUBrKLk4VXQjs09mu_6AhmU',
    appId: '1:535166613531:android:2aef70fdd3162f58eba0be',
    messagingSenderId: '535166613531',
    projectId: 'cosmicbrain-1360a',
    storageBucket: 'cosmicbrain-1360a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8bPIY9Y0B2ReGQBVGvRVZW6wno_QTndM',
    appId: '1:535166613531:ios:04fd08e754e3d5ddeba0be',
    messagingSenderId: '535166613531',
    projectId: 'cosmicbrain-1360a',
    storageBucket: 'cosmicbrain-1360a.firebasestorage.app',
    iosBundleId: 'com.example.cosmicBrainGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8bPIY9Y0B2ReGQBVGvRVZW6wno_QTndM',
    appId: '1:535166613531:ios:04fd08e754e3d5ddeba0be',
    messagingSenderId: '535166613531',
    projectId: 'cosmicbrain-1360a',
    storageBucket: 'cosmicbrain-1360a.firebasestorage.app',
    iosBundleId: 'com.example.cosmicBrainGames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqW4Vbv2fxD-2tRjaFQG2k2gs2sVnWn5o',
    appId: '1:535166613531:web:5081c71b309f8ca7eba0be',
    messagingSenderId: '535166613531',
    projectId: 'cosmicbrain-1360a',
    authDomain: 'cosmicbrain-1360a.firebaseapp.com',
    storageBucket: 'cosmicbrain-1360a.firebasestorage.app',
    measurementId: 'G-BKWQG1FPVQ',
  );
}
